const content = [
  "# Specifications",
  "",
  "Product: AskGaius 0.01",
  `Creation Date: ${new Date().toUTCString()}`,
  "",
  "",
  "",
  "# What is AskGaius?",
  "",
  "AskGaius is a portable AI assistant stored on a plug in and play device that works offline and does not send data to a remote server.",
  "",
  "",
  "",
  "# How to Start AskGaius",
  "",
  "## Microsoft Windows",
  "",
  "1. After inserting the AskGaius Stick, open the directory 'AskGaius' and double-click start_windows.bat",
  "",
  "2. This opens the terminal which will instruct you visit http://localhost:8080. Visit this website using a browser that supports WebGPU (e.g. Google Chrome or Microsoft Edge).",
  "",
  "You can visit the website https://webgpureport.org/ beforehand to verify if WebGPU is supported.",
  "",
  "3. To terminate AskGaius, close the browser, close the terminal and then safely remove the AskGaius Stick.",
  "",
  "",
  "## Linux",
  "",
  "1. After inserting the AskGaius Stick, open the directory 'AskGaius' in the terminal.  Type `bash ./start-linux.sh` and press the 'enter' key to run the executable",
  "",
  "2. The terminal will instruct you to visit http://localhost:8080. Visit this website using a browser that supports WebGPU (e.g. Google Chrome or Microsoft Edge).",
  "",
  "You can visit the website https://webgpureport.org/ beforehand to verify if WebGPU is supported.",
  "",
  "3. To terminate AskGaius, close the browser, close the terminal and then safely remove the AskGaius Stick.",
  "",
  "",
  "## macOS",
  "",
  "1. After inserting the AskGaius Stick, open the directory 'AskGaius' and double-click `start_macos.command`.",
  "",
  "2. The terminal will instruct you to visit http://localhost:8080. Visit this website using a browser that supports WebGPU (e.g. Google Chrome or Microsoft Edge).",
  "",
  "You can visit the website https://webgpureport.org/ beforehand to verify if WebGPU is supported.",
  "",
  "3. To terminate AskGaius, close the browser, close the terminal and then safely remove the AskGaius Stick.",
  "",
  "",
  "",
  "# How to Backup your Conversations",
  "",
  "- Click 'Download Backup' on the Home Page",
  "- This downloads a file called 'semper'",
  "- Place the 'semper' file in the same directory as the 'README.txt' (the file you are reading currently)",
];

await Bun.write("./AskGaius/README.txt", content.join("\n"));
