const content = [
  "# Specifications",
  "",
  "Product: AskGaius Mercury 0.01",
  `Creation Date: ${new Date().toUTCString()}`,
  "",
  "",
  "",
  "# What is AskGaius?",
  "",
  "AskGaius provides a Conversational AI Assistant on a memory card. All data is stored on the memory card and processed using the modern browser's WebGPU capabilities.",
  "",
  "",
  "",
  "# How to Start AskGaius",
  "",
  "## Microsoft Windows",
  "",
  "1. After inserting the AskGaius Memory Card, open the directory 'AskGaius' and then the directory 'exe'. Double click `askGaius-windows-x64.exe`",
  "",
  "2. This opens the terminal which will instruct you visit http://localhost:8080. Visit this website using a browser that supports WebGPU (e.g. Google Chrome or Microsoft Edge).",
  "",
  "You can visit the website https://webgpureport.org/ beforehand to verify if WebGPU is supported.",
  "",
  "3. To terminate AskGaius, close the browser, close the terminal and then safely remove the Memory Card.",
  "",
  "",
  "## Linux",
  "",
  "1. After inserting the AskGaius Memory Card, open the directory 'AskGaius' and then the directory 'exe' in the terminal. Run the executable `askGaius-linux-x64.exe`",
  "",
  "2. This opens the terminal which will instruct you visit http://localhost:8080. Visit this website using a browser that supports WebGPU (e.g. Google Chrome or Microsoft Edge).",
  "",
  "You can visit the website https://webgpureport.org/ beforehand to verify if WebGPU is supported.",
  "",
  "3. To terminate AskGaius, close the browser, close the terminal and then safely remove the Memory Card.",
  "",
  "",
  "## If you have an ARM64",
  "",
  "- If you have Windows and ARM64, click on the executable AskGaius/exe/askGaius-windows-arm64.exe",
  "",
  "- If you have Macos and ARM64, click on the executable AskGaius/exe/askGaius-linux-arm64.exe",
];

await Bun.write("./output/README.txt", content.join("\n"));
